class form:
    First_NAME = "Hashir"
    Last_NAME = "Khan"
    invalid_email = "hashirkhan.com"
    invalidAge = "yui"
    validsalary = "50000"
    Department_name = "SQA"
    valid_email = "hashirkhan@gmail.com.com"
    validAge = "25"
    invalid_Search_name = "Chat"
    valid_Search_name = "Hashir"
    edit_salary = "8888"
    dobuble_text = "You have done a double click"
    right_click_text = "You have done a right click"
    click_me_text = "You have done a dynamic click"
    file_path = r"E:\sampleFile.jpeg"
