class Locators:
    add_btn = "//button[@class='btn btn-primary']"
    submit_btn = "//button[contains(text(),'Submit')]"
    firstName = "(//input[@class=' mr-sm-2 form-control'])[1]"
    lastName = "(//input[@class=' mr-sm-2 form-control'])[2]"
    Email = "//input[@class='mr-sm-2 form-control']"
    age = "(//input[@class=' mr-sm-2 form-control'])[3]"
    salary = "(//input[@class=' mr-sm-2 form-control'])[4]"
    department = "(//input[@class=' mr-sm-2 form-control'])[5]"
    search = "//input[@class='form-control']"
    edit_btn = "//span[@class='mr-2']"
    delete = "//span[@id='delete-record-4']"
    side_button = "(//li[@id='item-4'])[1]"
    double_btn = "(//button[@class='btn btn-primary'])[1]"
    dobuble_btn_text = "//p[text()='You have done a double click']"
    right_click_btn = "(//button[@class='btn btn-primary'])[2]"
    right_click_btn_text = "//p[text()='You have done a right click']"
    click_me_btn = "(//button[@class='btn btn-primary'])[3]"
    click_me_btn_text = "//p[text()='You have done a dynamic click']"
    upload_image = "(//li[@id='item-7'])[1]"
    file_btn = "//input[@class='form-control-file']"